require 'rubygems'
require 'rest_client'
require 'json'
require 'rspec'

require 'mixcloud/popular_new_hot'
require 'mixcloud/url_helper'
require 'mixcloud/resource'
require 'mixcloud/artist'
require 'mixcloud/category'
require 'mixcloud/cloudcast'
require 'mixcloud/section'
require 'mixcloud/tag'
require 'mixcloud/track'
require 'mixcloud/user'
require 'mixcloud/search'
